/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow strict-local
 */

import React from 'react';
import type {Node} from 'react';
import {
  SafeAreaView,
  ScrollView,
  StatusBar,
  StyleSheet,
  Text,
  TouchableOpacity,
  useColorScheme,
  View,
} from 'react-native';

import PushNotification from 'react-native-push-notification';

const App: () => Node = () => {
  PushNotification.setApplicationIconBadgeNumber(0)
  function clicker() {
    console.log('in clicker function')
    PushNotification.localNotificationSchedule({
      date: new Date(Date.now() + 5 * 1000), // in 30 secs

      largeIcon: 'ic_launcher', // (optional) default: "ic_launcher"
      smallIcon: 'ic_notification', // (optional) default: "ic_notification" with fallback for "ic_launcher"
      vibrate: true, // (optional) default: true
      vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000       

      /* iOS and Android properties */
      title: 'iGAM - Your Personal Dentist', // (optional)
      message: "message", // (required)
      userInfo: {sceen: "home"}, // (optional) default: {} (using null throws a JSON value '<null>' error)
      number: 1, // (optional) Valid 32 bit integer specified as string. default: none (Cannot be zero)

    });
  }

  function creactMultNoti() {
    let time = []
    for (let i = 0; i < 3; i++) {
      time[i] = new Date(Date.now() + 5 * i * 1000) //every 5 seconds


      PushNotification.localNotificationSchedule({
        date: time[i], // in 30 secs

        /* Android Only Properties */
        //  channelId: soundName ? 'sound-channel-id' : 'default-channel-id',
        ticker: 'My Notification Ticker', // (optional)
        autoCancel: true, // (optional) default: true
        largeIcon: 'ic_launcher', // (optional) default: "ic_launcher"
        smallIcon: 'ic_notification', // (optional) default: "ic_notification" with fallback for "ic_launcher"
        bigText: 'My <strong>big text</strong> that will be shown when notification is expanded', // (optional) default: "message" prop
        subText: 'This is a subText', // (optional) default: none
        color: 'blue', // (optional) default: system default
        vibrate: true, // (optional) default: true
        vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
        tag: 'some_tag', // (optional) add tag to message
        group: 'group', // (optional) add group to message
        groupSummary: false, // (optional) set this notification to be the group summary for a group of notifications, default: false
        ongoing: false, // (optional) set whether this is an "ongoing" notification
        actions: ['Yes', 'No'], // (Android only) See the doc for notification actions to know more
        invokeApp: false, // (optional) This enable click on actions to bring back the application to foreground or stay in background, default: true

        when: null, // (optionnal) Add a timestamp pertaining to the notification (usually the time the event occurred). For apps targeting Build.VERSION_CODES.N and above, this time is not shown anymore by default and must be opted into by using `showWhen`, default: null.
        usesChronometer: false, // (optional) Show the `when` field as a stopwatch. Instead of presenting `when` as a timestamp, the notification will show an automatically updating display of the minutes and seconds since when. Useful when showing an elapsed time (like an ongoing phone call), default: false.
        timeoutAfter: null, // (optional) Specifies a duration in milliseconds after which this notification should be canceled, if it is not already canceled, default: null

        /* iOS only properties */
        category: '', // (optional) default: empty string

        /* iOS and Android properties */
        // id: this.lastId, // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
        title: 'Scheduled Notification', // (optional)
        message: 'My Notification Message', // (required)
        userInfo: {sceen: "home"}, // (optional) default: {} (using null throws a JSON value '<null>' error)
        // playSound: !!soundName, // (optional) default: true
        // soundName: soundName ? soundName : 'default', // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
        number: 1, // (optional) Valid 32 bit integer specified as string. default: none (Cannot be zero)
      });
    }
  }
  return (
    <View style={styles.main}>
      <TouchableOpacity style={styles.button} onPress={() => {clicker()}}>
        <Text style={styles.WT}>Press to notifi 30sec from now</Text>
      </TouchableOpacity>
      <TouchableOpacity style={styles.button} onPress={() => {creactMultNoti()}}>
        <Text style={styles.WT}>Press to notifi 3 in a row</Text>
      </TouchableOpacity>

      <TouchableOpacity style={styles.button} onPress={() => {
        PushNotification.getScheduledLocalNotifications(
          list => console.log(list)
        )
      }}>
        <Text style={styles.WT}>display the schedualed notification</Text>
      </TouchableOpacity>
      <TouchableOpacity style={styles.button} onPress={() => {PushNotification.removeAllDeliveredNotifications();}}>
        <Text style={styles.WT}>clears the notification center</Text>
      </TouchableOpacity>

      <TouchableOpacity style={styles.button} onPress={PushNotification.cancelAllLocalNotifications()}>
        <Text style={styles.WT}>cancel all notifications</Text>
      </TouchableOpacity>


    </View>
  );
};

const styles = StyleSheet.create({
  main: {
    backgroundColor: '#888',
    padding: 15,
    justifyContent: 'center',
    alignSelf: 'center',
    flex: 1,
  },
  button: {
    backgroundColor: '#aaa',
    borderWidth: 5,
    padding: 10,
    alignItems: 'center',
    borderRadius: 15,
  },
  WT: {
    color: '#fff',
    fontSize: 23
  },

});

export default App;
